---
# Set timezone
- name: Set timezone to America/New_York
  community.general.timezone:
    name: America/New_York

# Set DNS server to 9.9.9.9, backup to 8.8.8.8
#The regexp option tells the module what will be the content to replace.
#The line option replaces the previously found content with the new content of your choice.
#The backrefs option guarantees that if the regexp does not match, the file will be left unchanged.
- name: replace line in /etc/resolv.conf to add 9.9.9.9 and 8.8.8.8 nameservers
  lineinfile: 
    path: /etc/resolv.conf 
    regexp: '^nameserver(.*)$' 
    line: 'nameserver 9.9.9.9\nnameserver 8.8.8.8'
    backrefs: yes

# Update repositories
- name: Update apt package lists
  ansible.builtin.apt:
    update_cache: true

- name: Ensure apt-transport-https package is installed
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Configure sources.list to use HTTPS
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: '^(deb\s+)http(://http.kali.org/kali.*)$'
    replace: '\1https\2'

- shell: ls
  register: apt_result

- name: Update all packages to the latest version
  ansible.builtin.apt:
    upgrade: safe
    register: apt_result

- debug:
  var: apt_result.stderr

# Configure some update settings
- name: Disable apt systemd timers
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - apt-daily.timer
    - apt-daily-upgrade.timer

- name: Prevent apt services from running
  ansible.builtin.systemd:
    name: "{{ item }}"
    masked: true
  loop:
    - apt-daily.service
    - apt-daily-upgrade.service

# Create the desired file structure
- name: Create necessary directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  loop:
    - /home/{{user}}/uploads
    - /home/{{user}}/tools
    - /home/{{user}}/exploits
    - /home/{{user}}/bin
    - /home/{{user}}/scripts
    - /home/{{user}}/wordlists
    - /home/{{user}}/htb
    - /home/{{user}}/ctf
    - /home/{{user}}/.fonts
    - /home/{{user}}/.vscode
    - /opt/tmp
